2021-04-22T03:50:20.938640700Z -- Attaching packages --------------------------------------- tidyverse 1.3.0 --
2021-04-22T03:50:20.951977500Z v ggplot2 3.3.2     v purrr   0.3.4
2021-04-22T03:50:20.951998800Z v tibble  3.0.3     v dplyr   1.0.2
2021-04-22T03:50:20.952006900Z v tidyr   1.1.2     v stringr 1.4.0
2021-04-22T03:50:20.952013900Z v readr   1.3.1     v forcats 0.5.0
2021-04-22T03:50:21.127062900Z -- Conflicts ------------------------------------------ tidyverse_conflicts() --
2021-04-22T03:50:21.127119300Z x dplyr::filter() masks stats::filter()
2021-04-22T03:50:21.127128000Z x dplyr::lag()    masks stats::lag()
2021-04-22T03:50:21.140684700Z 
2021-04-22T03:50:21.140738000Z Attaching package: 'glue'
2021-04-22T03:50:21.140747000Z 
2021-04-22T03:50:21.142013800Z The following object is masked from 'package:dplyr':
2021-04-22T03:50:21.142034300Z 
2021-04-22T03:50:21.142043000Z     collapse
2021-04-22T03:50:21.142050600Z 
2021-04-22T03:50:23.311342000Z 
2021-04-22T03:50:23.311384800Z Attaching package: 'lubridate'
2021-04-22T03:50:23.311393100Z 
2021-04-22T03:50:23.311913400Z The following objects are masked from 'package:base':
2021-04-22T03:50:23.311929700Z 
2021-04-22T03:50:23.311937700Z     date, intersect, setdiff, union
2021-04-22T03:50:23.311944600Z 
2021-04-22T03:50:23.658440100Z <environment: R_GlobalEnv>
2021-04-22T03:50:23.658988600Z <environment: R_GlobalEnv>
2021-04-22T03:50:53.798452800Z data_pt data size = 7606081 
2021-04-22T03:50:53.800686500Z   memory usage = 3.073 GB 
2021-04-22T03:50:54.341592600Z     
2021-04-22T03:50:54.341627600Z all   
2021-04-22T03:50:54.341636500Z   
2021-04-22T03:51:01.968668700Z   
2021-04-22T03:51:02.219850600Z Error in eval(predvars, data, env) : object 'multimorb' not found
2021-04-22T03:51:02.219939500Z Calls: get_ipw_weights ... eval -> <Anonymous> -> model.frame.default -> eval -> eval
2021-04-22T03:51:02.244071500Z Backtrace:
2021-04-22T03:51:02.244284700Z 1: eval(predvars, data, env)
2021-04-22T03:51:02.244402000Z 2: eval(predvars, data, env)
2021-04-22T03:51:02.244527700Z 3: model.frame.default(formula = ipw_formula, data = data_atrisk, 
2021-04-22T03:51:02.244679200Z 4: stats::model.frame(formula = ipw_formula, data = data_atrisk, 
2021-04-22T03:51:02.244802300Z 5: eval(mf, parent.frame())
2021-04-22T03:51:02.244900800Z 6: eval(mf, parent.frame())
2021-04-22T03:51:02.245076700Z 7: glm(formula = ipw_formula, family = binomial, data = data_atrisk, 
2021-04-22T03:51:02.245260300Z 8: eval(cl, parent.frame())
2021-04-22T03:51:02.245419500Z 9: eval(cl, parent.frame())
2021-04-22T03:51:02.245476400Z 10: parglm(formula = ipw_formula, data = data_atrisk, family = binomial, 
2021-04-22T03:51:02.245674800Z 11: get_ipw_weights(data_pt_sub, "vaxany1", "vaxany1_status", "vaxany1_atrisk", 
2021-04-22T03:51:06.386765600Z vaxany1  

state: failed
commit: f1fd270c0518dd34d87dddd6887c60798415b647
docker_image_id: sha256:c2fc5042bf86134947d83ad8e70bd926e2c1f91a263c6bfe87438ad783bec981
exit_code: 1
job_id: c63dhpyx7ec6elmb
run_by_user: wjchulme
created_at: 2021-04-21T19:25:38Z
started_at: 2021-04-22T03:50:18Z
completed_at: 2021-04-22T03:51:33Z

Job exited with an error code

outputs:
  (no outputs)